version: "3.3"
volumes:
  data:
services:
  api_service:
    image: "isidromerayo/spring-backend-tfg:0.0.5"
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: "isidromerayo/mariadb-tfg:0.0.4"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ../recursos/db/create.mariadb.sql:/docker-entrypoint-initdb.d/create.mariadb.sql
      - ../recursos/db/dump.mariadb.sql:/docker-entrypoint-initdb.d/dump.mariadb.sql